site_name: Tech Writer Days
theme:
    name: material
    logo: TWD_logo.png
    favicon: TWD_logo.png
    features:
        - navigation.tabs
extra_css:
    - material-styles.css
nav:
    - HowTo:
        - Как запустить первый портал?: my-first-portal.md
    - FAQ: index.md
markdown_extensions:
    - pymdownx.superfences # более гибкое оформление блоков https://facelessuser.github.io/pymdown-extensions/extensions/superfences/
    - admonition