site_name: My Docs
theme:
    name: material
    logo: VK_WorkSpace.svg
    features:
        - navigation.tabs
extra_css:
    - material-styles.css
nav:
    - FAQ: index.md
    - HowTo:
        - Как запустить первый портал?: my-first-portal.md
markdown_extensions:
    - pymdownx.superfences # более гибкое оформление блоков https://facelessuser.github.io/pymdown-extensions/extensions/superfences/
    - admonition